feat: configure using kres, update to 2025.10.0
- Ensure clean and updatable build config
- push to ttl.sh
- Some mirrors are now offline since 2025.10.0 release, backport newer ones
- Newer busybox fails with libbb/hash_md5_sha.c:1316:35: error:
'sha1_process_block64_shaNI' undeclared; revert that update

Signed-off-by: Dmitrii Sharshakov <dmitry.sharshakov@siderolabs.com>